import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/layout/Header";
import Footer from "@/components/layout/Footer";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import StoreProvider from "@/providers/StoreProvider";
import AuthProvider from "@/providers/AuthProvider";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={"flex flex-col min-h-screen"}>
        <StoreProvider>
          <AuthProvider>
          <Header />
          <main className="flex-1 pt-20">{children}</main>
          <Footer className="mb-0" />
          </AuthProvider>
        </StoreProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
